### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#10]
```
var _Symbol = window.Symbol || function (description) {
              ^

ReferenceError: window is not defined
    at Object.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail-client/node_modules/iphone-inline-video/dist/iphone-inline-video.common-js.js:70:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail-client/src/wrappers/visuals/replay.js:3:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Happens when I run local unit tests with `tape test/**/*.test.js`

**Comment by binarykitchen** [comment]
thanks - any idea @bfred-it when you ll npm-publish that?

**Comment by bfred-it** [comment]
Already did!

**Comment by binarykitchen** [comment]
thanks - i am afraid, there is another bug ... will do a new ticket
