### ISSUE TITLE
Some warnings/errors when installing with npm v5.0.3

### ISSUE THREAD

**Issue by binarykitchen** [bfred-it/iphone-inline-video#129]
Just forked, cloned and did a `npm install`, showing a couple of issues here

```
┌─( ~/c/iphone-inline-video λ:master 63cd77c )──────────────────────────────────────────────────────────( @M1 )─┐
└─( 2 ) ❱❱❱ npm install                                                                           +2579 20:27 ❰─┘

> fsevents@1.0.17 install /home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/home/michael-heuberger/.nvm/versions/node/v8.1.0/bin/node',
node-pre-gyp verb cli   '/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.32.tgz
node-pre-gyp info using node@8.1.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:503:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:466:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:458:3)
node-pre-gyp ERR! System Linux 4.10.0-24-generic
node-pre-gyp ERR! command "/home/michael-heuberger/.nvm/versions/node/v8.1.0/bin/node" "/home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/michael-heuberger/code/iphone-inline-video/node_modules/fsevents
node-pre-gyp ERR! node -v v8.1.0
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.32.tgz
node-pre-gyp ERR! not ok 
Cannot read property 'version' of null
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> iphone-inline-video@2.2.0 prepublish /home/michael-heuberger/code/iphone-inline-video
> npm run build


> iphone-inline-video@2.2.0 build /home/michael-heuberger/code/iphone-inline-video
> npm-run-all --continue-on-error --silent jsfix build:*


  index.js:31:2
  ⚠  31:2  Unexpected todo comment.  no-warning-comments

  1 warning
Building:
• dist/iphone-inline-video.js
• dist/iphone-inline-video.min.js
• dist/iphone-inline-video.common-js.js
• dist/iphone-inline-video.es-modules.js
'intervalometer' is imported by index.js, but could not be resolved – treating it as an external dependency
┌───────────────────────────────────────────────┐
│                                               │
│   Bundle size: 4091 B, Gzipped size: 1622 B   │
│                                               │
└───────────────────────────────────────────────┘
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.0.17.tgz (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.17 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 740 packages in 37.546s
```

**Comment by bfred-it** [comment]
Thanks! Fixed in 2.2.1 (coming)
