### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by claudiocalautti** [bfred-it/iphone-inline-video#68]
Please handle "navigator" for when the module is loaded server side:

`ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/claudiocalautti/Projects/SomeProject/node_modules/iphone-inline-video/dist/iphone-inline-video.common-js.js:72:41)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/claudiocalautti/Projects/SomeProject/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (RandomHeroVideo.js:6:1)
    at Module._compile (module.js:409:26)`

**Comment by bfred-it** [comment]
IIV is meant to run on an iPhone, not server-side

**Comment by bfred-it** [comment]
May I ask how you resolved this issue?

**Comment by bfred-it** [comment]
#105
